/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model.impl;

import basic.model.EventHighLights;
import basic.model.EventHighLightsImageBlobModel;
import basic.model.EventHighLightsModel;
import basic.model.EventHighLightsSoap;

import basic.service.EventHighLightsLocalServiceUtil;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the EventHighLights service. Represents a row in the &quot;EventHighLights&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>EventHighLightsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EventHighLightsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EventHighLightsImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class EventHighLightsModelImpl
	extends BaseModelImpl<EventHighLights> implements EventHighLightsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a event high lights model instance should use the <code>EventHighLights</code> interface instead.
	 */
	public static final String TABLE_NAME = "EventHighLights";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"id_", Types.BIGINT},
		{"Title", Types.VARCHAR}, {"Description", Types.VARCHAR},
		{"Image", Types.BLOB}, {"eventId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Image", Types.BLOB);
		TABLE_COLUMNS_MAP.put("eventId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EventHighLights (uuid_ VARCHAR(75) null,id_ LONG not null primary key,Title VARCHAR(75) null,Description VARCHAR(75) null,Image BLOB,eventId VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table EventHighLights";

	public static final String ORDER_BY_JPQL =
		" ORDER BY eventHighLights.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EventHighLights.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long UUID_COLUMN_BITMASK = 1L;

	public static final long ID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EventHighLights toModel(EventHighLightsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EventHighLights model = new EventHighLightsImpl();

		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());
		model.setTitle(soapModel.getTitle());
		model.setDescription(soapModel.getDescription());
		model.setImage(soapModel.getImage());
		model.setEventId(soapModel.getEventId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EventHighLights> toModels(
		EventHighLightsSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<EventHighLights> models = new ArrayList<EventHighLights>(
			soapModels.length);

		for (EventHighLightsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EventHighLightsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EventHighLights.class;
	}

	@Override
	public String getModelClassName() {
		return EventHighLights.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EventHighLights, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EventHighLights, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EventHighLights, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EventHighLights)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EventHighLights, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EventHighLights, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EventHighLights)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EventHighLights, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EventHighLights, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EventHighLights>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EventHighLights.class.getClassLoader(), EventHighLights.class,
			ModelWrapper.class);

		try {
			Constructor<EventHighLights> constructor =
				(Constructor<EventHighLights>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<EventHighLights, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EventHighLights, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EventHighLights, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<EventHighLights, Object>>();
		Map<String, BiConsumer<EventHighLights, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EventHighLights, ?>>();

		attributeGetterFunctions.put("uuid", EventHighLights::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<EventHighLights, String>)EventHighLights::setUuid);
		attributeGetterFunctions.put("id", EventHighLights::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<EventHighLights, Long>)EventHighLights::setId);
		attributeGetterFunctions.put("Title", EventHighLights::getTitle);
		attributeSetterBiConsumers.put(
			"Title",
			(BiConsumer<EventHighLights, String>)EventHighLights::setTitle);
		attributeGetterFunctions.put(
			"Description", EventHighLights::getDescription);
		attributeSetterBiConsumers.put(
			"Description",
			(BiConsumer<EventHighLights, String>)
				EventHighLights::setDescription);
		attributeGetterFunctions.put("Image", EventHighLights::getImage);
		attributeSetterBiConsumers.put(
			"Image",
			(BiConsumer<EventHighLights, Blob>)EventHighLights::setImage);
		attributeGetterFunctions.put("eventId", EventHighLights::getEventId);
		attributeSetterBiConsumers.put(
			"eventId",
			(BiConsumer<EventHighLights, String>)EventHighLights::setEventId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_Title == null) {
			return "";
		}
		else {
			return _Title;
		}
	}

	@Override
	public void setTitle(String Title) {
		_Title = Title;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_Description == null) {
			return "";
		}
		else {
			return _Description;
		}
	}

	@Override
	public void setDescription(String Description) {
		_Description = Description;
	}

	@JSON
	@Override
	public Blob getImage() {
		if (_ImageBlobModel == null) {
			try {
				_ImageBlobModel =
					EventHighLightsLocalServiceUtil.getImageBlobModel(
						getPrimaryKey());
			}
			catch (Exception e) {
			}
		}

		Blob blob = null;

		if (_ImageBlobModel != null) {
			blob = _ImageBlobModel.getImageBlob();
		}

		return blob;
	}

	@Override
	public void setImage(Blob Image) {
		if (_ImageBlobModel == null) {
			_ImageBlobModel = new EventHighLightsImageBlobModel(
				getPrimaryKey(), Image);
		}
		else {
			_ImageBlobModel.setImageBlob(Image);
		}
	}

	@JSON
	@Override
	public String getEventId() {
		if (_eventId == null) {
			return "";
		}
		else {
			return _eventId;
		}
	}

	@Override
	public void setEventId(String eventId) {
		_eventId = eventId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, EventHighLights.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EventHighLights toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EventHighLights>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EventHighLightsImpl eventHighLightsImpl = new EventHighLightsImpl();

		eventHighLightsImpl.setUuid(getUuid());
		eventHighLightsImpl.setId(getId());
		eventHighLightsImpl.setTitle(getTitle());
		eventHighLightsImpl.setDescription(getDescription());
		eventHighLightsImpl.setEventId(getEventId());

		eventHighLightsImpl.resetOriginalValues();

		return eventHighLightsImpl;
	}

	@Override
	public int compareTo(EventHighLights eventHighLights) {
		long primaryKey = eventHighLights.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EventHighLights)) {
			return false;
		}

		EventHighLights eventHighLights = (EventHighLights)obj;

		long primaryKey = eventHighLights.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		EventHighLightsModelImpl eventHighLightsModelImpl = this;

		eventHighLightsModelImpl._originalUuid = eventHighLightsModelImpl._uuid;

		eventHighLightsModelImpl._ImageBlobModel = null;

		eventHighLightsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EventHighLights> toCacheModel() {
		EventHighLightsCacheModel eventHighLightsCacheModel =
			new EventHighLightsCacheModel();

		eventHighLightsCacheModel.uuid = getUuid();

		String uuid = eventHighLightsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			eventHighLightsCacheModel.uuid = null;
		}

		eventHighLightsCacheModel.id = getId();

		eventHighLightsCacheModel.Title = getTitle();

		String Title = eventHighLightsCacheModel.Title;

		if ((Title != null) && (Title.length() == 0)) {
			eventHighLightsCacheModel.Title = null;
		}

		eventHighLightsCacheModel.Description = getDescription();

		String Description = eventHighLightsCacheModel.Description;

		if ((Description != null) && (Description.length() == 0)) {
			eventHighLightsCacheModel.Description = null;
		}

		eventHighLightsCacheModel.eventId = getEventId();

		String eventId = eventHighLightsCacheModel.eventId;

		if ((eventId != null) && (eventId.length() == 0)) {
			eventHighLightsCacheModel.eventId = null;
		}

		return eventHighLightsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", id=");
		sb.append(getId());
		sb.append(", Title=");
		sb.append(getTitle());
		sb.append(", Description=");
		sb.append(getDescription());
		sb.append(", eventId=");
		sb.append(getEventId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("basic.model.EventHighLights");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eventId</column-name><column-value><![CDATA[");
		sb.append(getEventId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EventHighLights>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _id;
	private String _Title;
	private String _Description;
	private EventHighLightsImageBlobModel _ImageBlobModel;
	private String _eventId;
	private long _columnBitmask;
	private EventHighLights _escapedModel;

}