/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model.impl;

import basic.model.ProfileJobWishList;
import basic.model.ProfileJobWishListModel;
import basic.model.ProfileJobWishListSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the ProfileJobWishList service. Represents a row in the &quot;ProfileJobWishList&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ProfileJobWishListModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProfileJobWishListImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProfileJobWishListImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ProfileJobWishListModelImpl
	extends BaseModelImpl<ProfileJobWishList>
	implements ProfileJobWishListModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a profile job wish list model instance should use the <code>ProfileJobWishList</code> interface instead.
	 */
	public static final String TABLE_NAME = "ProfileJobWishList";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"Id", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"jobwishlist", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("jobwishlist", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ProfileJobWishList (uuid_ VARCHAR(75) null,Id LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,jobwishlist VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ProfileJobWishList";

	public static final String ORDER_BY_JPQL =
		" ORDER BY profileJobWishList.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ProfileJobWishList.Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long ID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ProfileJobWishList toModel(ProfileJobWishListSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ProfileJobWishList model = new ProfileJobWishListImpl();

		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setJobwishlist(soapModel.getJobwishlist());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ProfileJobWishList> toModels(
		ProfileJobWishListSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<ProfileJobWishList> models = new ArrayList<ProfileJobWishList>(
			soapModels.length);

		for (ProfileJobWishListSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ProfileJobWishListModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProfileJobWishList.class;
	}

	@Override
	public String getModelClassName() {
		return ProfileJobWishList.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProfileJobWishList, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProfileJobWishList, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProfileJobWishList, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProfileJobWishList)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProfileJobWishList, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProfileJobWishList, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProfileJobWishList)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProfileJobWishList, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProfileJobWishList, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ProfileJobWishList>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ProfileJobWishList.class.getClassLoader(), ProfileJobWishList.class,
			ModelWrapper.class);

		try {
			Constructor<ProfileJobWishList> constructor =
				(Constructor<ProfileJobWishList>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<ProfileJobWishList, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ProfileJobWishList, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProfileJobWishList, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ProfileJobWishList, Object>>();
		Map<String, BiConsumer<ProfileJobWishList, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ProfileJobWishList, ?>>();

		attributeGetterFunctions.put("uuid", ProfileJobWishList::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ProfileJobWishList, String>)
				ProfileJobWishList::setUuid);
		attributeGetterFunctions.put("Id", ProfileJobWishList::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<ProfileJobWishList, Long>)ProfileJobWishList::setId);
		attributeGetterFunctions.put("groupId", ProfileJobWishList::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ProfileJobWishList, Long>)
				ProfileJobWishList::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ProfileJobWishList::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ProfileJobWishList, Long>)
				ProfileJobWishList::setCompanyId);
		attributeGetterFunctions.put("userId", ProfileJobWishList::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ProfileJobWishList, Long>)
				ProfileJobWishList::setUserId);
		attributeGetterFunctions.put(
			"userName", ProfileJobWishList::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ProfileJobWishList, String>)
				ProfileJobWishList::setUserName);
		attributeGetterFunctions.put(
			"createDate", ProfileJobWishList::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ProfileJobWishList, Date>)
				ProfileJobWishList::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ProfileJobWishList::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ProfileJobWishList, Date>)
				ProfileJobWishList::setModifiedDate);
		attributeGetterFunctions.put(
			"jobwishlist", ProfileJobWishList::getJobwishlist);
		attributeSetterBiConsumers.put(
			"jobwishlist",
			(BiConsumer<ProfileJobWishList, String>)
				ProfileJobWishList::setJobwishlist);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		_Id = Id;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getJobwishlist() {
		if (_jobwishlist == null) {
			return "";
		}
		else {
			return _jobwishlist;
		}
	}

	@Override
	public void setJobwishlist(String jobwishlist) {
		_jobwishlist = jobwishlist;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ProfileJobWishList.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProfileJobWishList.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProfileJobWishList toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProfileJobWishList>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProfileJobWishListImpl profileJobWishListImpl =
			new ProfileJobWishListImpl();

		profileJobWishListImpl.setUuid(getUuid());
		profileJobWishListImpl.setId(getId());
		profileJobWishListImpl.setGroupId(getGroupId());
		profileJobWishListImpl.setCompanyId(getCompanyId());
		profileJobWishListImpl.setUserId(getUserId());
		profileJobWishListImpl.setUserName(getUserName());
		profileJobWishListImpl.setCreateDate(getCreateDate());
		profileJobWishListImpl.setModifiedDate(getModifiedDate());
		profileJobWishListImpl.setJobwishlist(getJobwishlist());

		profileJobWishListImpl.resetOriginalValues();

		return profileJobWishListImpl;
	}

	@Override
	public int compareTo(ProfileJobWishList profileJobWishList) {
		long primaryKey = profileJobWishList.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ProfileJobWishList)) {
			return false;
		}

		ProfileJobWishList profileJobWishList = (ProfileJobWishList)obj;

		long primaryKey = profileJobWishList.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ProfileJobWishListModelImpl profileJobWishListModelImpl = this;

		profileJobWishListModelImpl._originalUuid =
			profileJobWishListModelImpl._uuid;

		profileJobWishListModelImpl._originalGroupId =
			profileJobWishListModelImpl._groupId;

		profileJobWishListModelImpl._setOriginalGroupId = false;

		profileJobWishListModelImpl._originalCompanyId =
			profileJobWishListModelImpl._companyId;

		profileJobWishListModelImpl._setOriginalCompanyId = false;

		profileJobWishListModelImpl._setModifiedDate = false;

		profileJobWishListModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ProfileJobWishList> toCacheModel() {
		ProfileJobWishListCacheModel profileJobWishListCacheModel =
			new ProfileJobWishListCacheModel();

		profileJobWishListCacheModel.uuid = getUuid();

		String uuid = profileJobWishListCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			profileJobWishListCacheModel.uuid = null;
		}

		profileJobWishListCacheModel.Id = getId();

		profileJobWishListCacheModel.groupId = getGroupId();

		profileJobWishListCacheModel.companyId = getCompanyId();

		profileJobWishListCacheModel.userId = getUserId();

		profileJobWishListCacheModel.userName = getUserName();

		String userName = profileJobWishListCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			profileJobWishListCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			profileJobWishListCacheModel.createDate = createDate.getTime();
		}
		else {
			profileJobWishListCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			profileJobWishListCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			profileJobWishListCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		profileJobWishListCacheModel.jobwishlist = getJobwishlist();

		String jobwishlist = profileJobWishListCacheModel.jobwishlist;

		if ((jobwishlist != null) && (jobwishlist.length() == 0)) {
			profileJobWishListCacheModel.jobwishlist = null;
		}

		return profileJobWishListCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProfileJobWishList, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProfileJobWishList, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProfileJobWishList, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ProfileJobWishList)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ProfileJobWishList, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ProfileJobWishList, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProfileJobWishList, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ProfileJobWishList)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProfileJobWishList>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _Id;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _jobwishlist;
	private long _columnBitmask;
	private ProfileJobWishList _escapedModel;

}