/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model.impl;

import basic.model.ProfileTestimonial;
import basic.model.ProfileTestimonialModel;
import basic.model.ProfileTestimonialSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the ProfileTestimonial service. Represents a row in the &quot;ProfileTestimonial&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ProfileTestimonialModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProfileTestimonialImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProfileTestimonialImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ProfileTestimonialModelImpl
	extends BaseModelImpl<ProfileTestimonial>
	implements ProfileTestimonialModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a profile testimonial model instance should use the <code>ProfileTestimonial</code> interface instead.
	 */
	public static final String TABLE_NAME = "ProfileTestimonial";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"id_", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"testimonialprovidername", Types.VARCHAR},
		{"testimonialprovideremail", Types.VARCHAR},
		{"testimonialprovorgname", Types.VARCHAR},
		{"testimonialprovidertitle", Types.VARCHAR},
		{"testimonialprivatemessage", Types.VARCHAR},
		{"imagePreview", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("testimonialprovidername", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("testimonialprovideremail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("testimonialprovorgname", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("testimonialprovidertitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("testimonialprivatemessage", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imagePreview", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ProfileTestimonial (uuid_ VARCHAR(75) null,id_ LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,testimonialprovidername VARCHAR(75) null,testimonialprovideremail VARCHAR(75) null,testimonialprovorgname VARCHAR(75) null,testimonialprovidertitle VARCHAR(75) null,testimonialprivatemessage VARCHAR(75) null,imagePreview VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ProfileTestimonial";

	public static final String ORDER_BY_JPQL =
		" ORDER BY profileTestimonial.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ProfileTestimonial.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long ID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ProfileTestimonial toModel(ProfileTestimonialSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ProfileTestimonial model = new ProfileTestimonialImpl();

		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTestimonialprovidername(
			soapModel.getTestimonialprovidername());
		model.setTestimonialprovideremail(
			soapModel.getTestimonialprovideremail());
		model.setTestimonialprovorgname(soapModel.getTestimonialprovorgname());
		model.setTestimonialprovidertitle(
			soapModel.getTestimonialprovidertitle());
		model.setTestimonialprivatemessage(
			soapModel.getTestimonialprivatemessage());
		model.setImagePreview(soapModel.getImagePreview());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ProfileTestimonial> toModels(
		ProfileTestimonialSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<ProfileTestimonial> models = new ArrayList<ProfileTestimonial>(
			soapModels.length);

		for (ProfileTestimonialSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ProfileTestimonialModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProfileTestimonial.class;
	}

	@Override
	public String getModelClassName() {
		return ProfileTestimonial.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProfileTestimonial, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProfileTestimonial, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProfileTestimonial, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProfileTestimonial)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProfileTestimonial, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProfileTestimonial, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProfileTestimonial)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProfileTestimonial, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProfileTestimonial, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ProfileTestimonial>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ProfileTestimonial.class.getClassLoader(), ProfileTestimonial.class,
			ModelWrapper.class);

		try {
			Constructor<ProfileTestimonial> constructor =
				(Constructor<ProfileTestimonial>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<ProfileTestimonial, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ProfileTestimonial, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProfileTestimonial, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ProfileTestimonial, Object>>();
		Map<String, BiConsumer<ProfileTestimonial, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ProfileTestimonial, ?>>();

		attributeGetterFunctions.put("uuid", ProfileTestimonial::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ProfileTestimonial, String>)
				ProfileTestimonial::setUuid);
		attributeGetterFunctions.put("id", ProfileTestimonial::getId);
		attributeSetterBiConsumers.put(
			"id",
			(BiConsumer<ProfileTestimonial, Long>)ProfileTestimonial::setId);
		attributeGetterFunctions.put("groupId", ProfileTestimonial::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ProfileTestimonial, Long>)
				ProfileTestimonial::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ProfileTestimonial::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ProfileTestimonial, Long>)
				ProfileTestimonial::setCompanyId);
		attributeGetterFunctions.put("userId", ProfileTestimonial::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ProfileTestimonial, Long>)
				ProfileTestimonial::setUserId);
		attributeGetterFunctions.put(
			"userName", ProfileTestimonial::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ProfileTestimonial, String>)
				ProfileTestimonial::setUserName);
		attributeGetterFunctions.put(
			"createDate", ProfileTestimonial::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ProfileTestimonial, Date>)
				ProfileTestimonial::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ProfileTestimonial::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ProfileTestimonial, Date>)
				ProfileTestimonial::setModifiedDate);
		attributeGetterFunctions.put(
			"testimonialprovidername",
			ProfileTestimonial::getTestimonialprovidername);
		attributeSetterBiConsumers.put(
			"testimonialprovidername",
			(BiConsumer<ProfileTestimonial, String>)
				ProfileTestimonial::setTestimonialprovidername);
		attributeGetterFunctions.put(
			"testimonialprovideremail",
			ProfileTestimonial::getTestimonialprovideremail);
		attributeSetterBiConsumers.put(
			"testimonialprovideremail",
			(BiConsumer<ProfileTestimonial, String>)
				ProfileTestimonial::setTestimonialprovideremail);
		attributeGetterFunctions.put(
			"testimonialprovorgname",
			ProfileTestimonial::getTestimonialprovorgname);
		attributeSetterBiConsumers.put(
			"testimonialprovorgname",
			(BiConsumer<ProfileTestimonial, String>)
				ProfileTestimonial::setTestimonialprovorgname);
		attributeGetterFunctions.put(
			"testimonialprovidertitle",
			ProfileTestimonial::getTestimonialprovidertitle);
		attributeSetterBiConsumers.put(
			"testimonialprovidertitle",
			(BiConsumer<ProfileTestimonial, String>)
				ProfileTestimonial::setTestimonialprovidertitle);
		attributeGetterFunctions.put(
			"testimonialprivatemessage",
			ProfileTestimonial::getTestimonialprivatemessage);
		attributeSetterBiConsumers.put(
			"testimonialprivatemessage",
			(BiConsumer<ProfileTestimonial, String>)
				ProfileTestimonial::setTestimonialprivatemessage);
		attributeGetterFunctions.put(
			"imagePreview", ProfileTestimonial::getImagePreview);
		attributeSetterBiConsumers.put(
			"imagePreview",
			(BiConsumer<ProfileTestimonial, String>)
				ProfileTestimonial::setImagePreview);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTestimonialprovidername() {
		if (_testimonialprovidername == null) {
			return "";
		}
		else {
			return _testimonialprovidername;
		}
	}

	@Override
	public void setTestimonialprovidername(String testimonialprovidername) {
		_testimonialprovidername = testimonialprovidername;
	}

	@JSON
	@Override
	public String getTestimonialprovideremail() {
		if (_testimonialprovideremail == null) {
			return "";
		}
		else {
			return _testimonialprovideremail;
		}
	}

	@Override
	public void setTestimonialprovideremail(String testimonialprovideremail) {
		_testimonialprovideremail = testimonialprovideremail;
	}

	@JSON
	@Override
	public String getTestimonialprovorgname() {
		if (_testimonialprovorgname == null) {
			return "";
		}
		else {
			return _testimonialprovorgname;
		}
	}

	@Override
	public void setTestimonialprovorgname(String testimonialprovorgname) {
		_testimonialprovorgname = testimonialprovorgname;
	}

	@JSON
	@Override
	public String getTestimonialprovidertitle() {
		if (_testimonialprovidertitle == null) {
			return "";
		}
		else {
			return _testimonialprovidertitle;
		}
	}

	@Override
	public void setTestimonialprovidertitle(String testimonialprovidertitle) {
		_testimonialprovidertitle = testimonialprovidertitle;
	}

	@JSON
	@Override
	public String getTestimonialprivatemessage() {
		if (_testimonialprivatemessage == null) {
			return "";
		}
		else {
			return _testimonialprivatemessage;
		}
	}

	@Override
	public void setTestimonialprivatemessage(String testimonialprivatemessage) {
		_testimonialprivatemessage = testimonialprivatemessage;
	}

	@JSON
	@Override
	public String getImagePreview() {
		if (_imagePreview == null) {
			return "";
		}
		else {
			return _imagePreview;
		}
	}

	@Override
	public void setImagePreview(String imagePreview) {
		_imagePreview = imagePreview;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ProfileTestimonial.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProfileTestimonial.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProfileTestimonial toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProfileTestimonial>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProfileTestimonialImpl profileTestimonialImpl =
			new ProfileTestimonialImpl();

		profileTestimonialImpl.setUuid(getUuid());
		profileTestimonialImpl.setId(getId());
		profileTestimonialImpl.setGroupId(getGroupId());
		profileTestimonialImpl.setCompanyId(getCompanyId());
		profileTestimonialImpl.setUserId(getUserId());
		profileTestimonialImpl.setUserName(getUserName());
		profileTestimonialImpl.setCreateDate(getCreateDate());
		profileTestimonialImpl.setModifiedDate(getModifiedDate());
		profileTestimonialImpl.setTestimonialprovidername(
			getTestimonialprovidername());
		profileTestimonialImpl.setTestimonialprovideremail(
			getTestimonialprovideremail());
		profileTestimonialImpl.setTestimonialprovorgname(
			getTestimonialprovorgname());
		profileTestimonialImpl.setTestimonialprovidertitle(
			getTestimonialprovidertitle());
		profileTestimonialImpl.setTestimonialprivatemessage(
			getTestimonialprivatemessage());
		profileTestimonialImpl.setImagePreview(getImagePreview());

		profileTestimonialImpl.resetOriginalValues();

		return profileTestimonialImpl;
	}

	@Override
	public int compareTo(ProfileTestimonial profileTestimonial) {
		long primaryKey = profileTestimonial.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ProfileTestimonial)) {
			return false;
		}

		ProfileTestimonial profileTestimonial = (ProfileTestimonial)obj;

		long primaryKey = profileTestimonial.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ProfileTestimonialModelImpl profileTestimonialModelImpl = this;

		profileTestimonialModelImpl._originalUuid =
			profileTestimonialModelImpl._uuid;

		profileTestimonialModelImpl._originalGroupId =
			profileTestimonialModelImpl._groupId;

		profileTestimonialModelImpl._setOriginalGroupId = false;

		profileTestimonialModelImpl._originalCompanyId =
			profileTestimonialModelImpl._companyId;

		profileTestimonialModelImpl._setOriginalCompanyId = false;

		profileTestimonialModelImpl._setModifiedDate = false;

		profileTestimonialModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ProfileTestimonial> toCacheModel() {
		ProfileTestimonialCacheModel profileTestimonialCacheModel =
			new ProfileTestimonialCacheModel();

		profileTestimonialCacheModel.uuid = getUuid();

		String uuid = profileTestimonialCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			profileTestimonialCacheModel.uuid = null;
		}

		profileTestimonialCacheModel.id = getId();

		profileTestimonialCacheModel.groupId = getGroupId();

		profileTestimonialCacheModel.companyId = getCompanyId();

		profileTestimonialCacheModel.userId = getUserId();

		profileTestimonialCacheModel.userName = getUserName();

		String userName = profileTestimonialCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			profileTestimonialCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			profileTestimonialCacheModel.createDate = createDate.getTime();
		}
		else {
			profileTestimonialCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			profileTestimonialCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			profileTestimonialCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		profileTestimonialCacheModel.testimonialprovidername =
			getTestimonialprovidername();

		String testimonialprovidername =
			profileTestimonialCacheModel.testimonialprovidername;

		if ((testimonialprovidername != null) &&
			(testimonialprovidername.length() == 0)) {

			profileTestimonialCacheModel.testimonialprovidername = null;
		}

		profileTestimonialCacheModel.testimonialprovideremail =
			getTestimonialprovideremail();

		String testimonialprovideremail =
			profileTestimonialCacheModel.testimonialprovideremail;

		if ((testimonialprovideremail != null) &&
			(testimonialprovideremail.length() == 0)) {

			profileTestimonialCacheModel.testimonialprovideremail = null;
		}

		profileTestimonialCacheModel.testimonialprovorgname =
			getTestimonialprovorgname();

		String testimonialprovorgname =
			profileTestimonialCacheModel.testimonialprovorgname;

		if ((testimonialprovorgname != null) &&
			(testimonialprovorgname.length() == 0)) {

			profileTestimonialCacheModel.testimonialprovorgname = null;
		}

		profileTestimonialCacheModel.testimonialprovidertitle =
			getTestimonialprovidertitle();

		String testimonialprovidertitle =
			profileTestimonialCacheModel.testimonialprovidertitle;

		if ((testimonialprovidertitle != null) &&
			(testimonialprovidertitle.length() == 0)) {

			profileTestimonialCacheModel.testimonialprovidertitle = null;
		}

		profileTestimonialCacheModel.testimonialprivatemessage =
			getTestimonialprivatemessage();

		String testimonialprivatemessage =
			profileTestimonialCacheModel.testimonialprivatemessage;

		if ((testimonialprivatemessage != null) &&
			(testimonialprivatemessage.length() == 0)) {

			profileTestimonialCacheModel.testimonialprivatemessage = null;
		}

		profileTestimonialCacheModel.imagePreview = getImagePreview();

		String imagePreview = profileTestimonialCacheModel.imagePreview;

		if ((imagePreview != null) && (imagePreview.length() == 0)) {
			profileTestimonialCacheModel.imagePreview = null;
		}

		return profileTestimonialCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProfileTestimonial, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProfileTestimonial, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProfileTestimonial, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ProfileTestimonial)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ProfileTestimonial, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ProfileTestimonial, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProfileTestimonial, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ProfileTestimonial)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProfileTestimonial>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _id;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _testimonialprovidername;
	private String _testimonialprovideremail;
	private String _testimonialprovorgname;
	private String _testimonialprovidertitle;
	private String _testimonialprivatemessage;
	private String _imagePreview;
	private long _columnBitmask;
	private ProfileTestimonial _escapedModel;

}