/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model.impl;

import basic.model.EventFAQs;
import basic.model.EventFAQsModel;
import basic.model.EventFAQsSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the EventFAQs service. Represents a row in the &quot;EventFAQs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>EventFAQsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EventFAQsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EventFAQsImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class EventFAQsModelImpl
	extends BaseModelImpl<EventFAQs> implements EventFAQsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a event fa qs model instance should use the <code>EventFAQs</code> interface instead.
	 */
	public static final String TABLE_NAME = "EventFAQs";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"id_", Types.BIGINT},
		{"Question", Types.VARCHAR}, {"Answer", Types.VARCHAR},
		{"eventId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Question", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Answer", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EventFAQs (uuid_ VARCHAR(75) null,id_ LONG not null primary key,Question VARCHAR(75) null,Answer VARCHAR(75) null,eventId VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table EventFAQs";

	public static final String ORDER_BY_JPQL = " ORDER BY eventFAQs.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY EventFAQs.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long UUID_COLUMN_BITMASK = 1L;

	public static final long ID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EventFAQs toModel(EventFAQsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EventFAQs model = new EventFAQsImpl();

		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());
		model.setQuestion(soapModel.getQuestion());
		model.setAnswer(soapModel.getAnswer());
		model.setEventId(soapModel.getEventId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EventFAQs> toModels(EventFAQsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EventFAQs> models = new ArrayList<EventFAQs>(soapModels.length);

		for (EventFAQsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EventFAQsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EventFAQs.class;
	}

	@Override
	public String getModelClassName() {
		return EventFAQs.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EventFAQs, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EventFAQs, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EventFAQs, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((EventFAQs)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EventFAQs, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EventFAQs, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EventFAQs)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EventFAQs, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EventFAQs, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EventFAQs>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EventFAQs.class.getClassLoader(), EventFAQs.class,
			ModelWrapper.class);

		try {
			Constructor<EventFAQs> constructor =
				(Constructor<EventFAQs>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<EventFAQs, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EventFAQs, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EventFAQs, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<EventFAQs, Object>>();
		Map<String, BiConsumer<EventFAQs, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EventFAQs, ?>>();

		attributeGetterFunctions.put("uuid", EventFAQs::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<EventFAQs, String>)EventFAQs::setUuid);
		attributeGetterFunctions.put("id", EventFAQs::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<EventFAQs, Long>)EventFAQs::setId);
		attributeGetterFunctions.put("Question", EventFAQs::getQuestion);
		attributeSetterBiConsumers.put(
			"Question", (BiConsumer<EventFAQs, String>)EventFAQs::setQuestion);
		attributeGetterFunctions.put("Answer", EventFAQs::getAnswer);
		attributeSetterBiConsumers.put(
			"Answer", (BiConsumer<EventFAQs, String>)EventFAQs::setAnswer);
		attributeGetterFunctions.put("eventId", EventFAQs::getEventId);
		attributeSetterBiConsumers.put(
			"eventId", (BiConsumer<EventFAQs, String>)EventFAQs::setEventId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getQuestion() {
		if (_Question == null) {
			return "";
		}
		else {
			return _Question;
		}
	}

	@Override
	public void setQuestion(String Question) {
		_Question = Question;
	}

	@JSON
	@Override
	public String getAnswer() {
		if (_Answer == null) {
			return "";
		}
		else {
			return _Answer;
		}
	}

	@Override
	public void setAnswer(String Answer) {
		_Answer = Answer;
	}

	@JSON
	@Override
	public String getEventId() {
		if (_eventId == null) {
			return "";
		}
		else {
			return _eventId;
		}
	}

	@Override
	public void setEventId(String eventId) {
		_eventId = eventId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, EventFAQs.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EventFAQs toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EventFAQs>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EventFAQsImpl eventFAQsImpl = new EventFAQsImpl();

		eventFAQsImpl.setUuid(getUuid());
		eventFAQsImpl.setId(getId());
		eventFAQsImpl.setQuestion(getQuestion());
		eventFAQsImpl.setAnswer(getAnswer());
		eventFAQsImpl.setEventId(getEventId());

		eventFAQsImpl.resetOriginalValues();

		return eventFAQsImpl;
	}

	@Override
	public int compareTo(EventFAQs eventFAQs) {
		long primaryKey = eventFAQs.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EventFAQs)) {
			return false;
		}

		EventFAQs eventFAQs = (EventFAQs)obj;

		long primaryKey = eventFAQs.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		EventFAQsModelImpl eventFAQsModelImpl = this;

		eventFAQsModelImpl._originalUuid = eventFAQsModelImpl._uuid;

		eventFAQsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EventFAQs> toCacheModel() {
		EventFAQsCacheModel eventFAQsCacheModel = new EventFAQsCacheModel();

		eventFAQsCacheModel.uuid = getUuid();

		String uuid = eventFAQsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			eventFAQsCacheModel.uuid = null;
		}

		eventFAQsCacheModel.id = getId();

		eventFAQsCacheModel.Question = getQuestion();

		String Question = eventFAQsCacheModel.Question;

		if ((Question != null) && (Question.length() == 0)) {
			eventFAQsCacheModel.Question = null;
		}

		eventFAQsCacheModel.Answer = getAnswer();

		String Answer = eventFAQsCacheModel.Answer;

		if ((Answer != null) && (Answer.length() == 0)) {
			eventFAQsCacheModel.Answer = null;
		}

		eventFAQsCacheModel.eventId = getEventId();

		String eventId = eventFAQsCacheModel.eventId;

		if ((eventId != null) && (eventId.length() == 0)) {
			eventFAQsCacheModel.eventId = null;
		}

		return eventFAQsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EventFAQs, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EventFAQs, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EventFAQs, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((EventFAQs)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EventFAQs, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EventFAQs, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EventFAQs, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EventFAQs)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EventFAQs>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _id;
	private String _Question;
	private String _Answer;
	private String _eventId;
	private long _columnBitmask;
	private EventFAQs _escapedModel;

}