/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model.impl;

import basic.model.EventAssigneeTable;
import basic.model.EventAssigneeTableModel;
import basic.model.EventAssigneeTableSoap;

import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the EventAssigneeTable service. Represents a row in the &quot;EventAssigneeTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>EventAssigneeTableModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EventAssigneeTableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EventAssigneeTableImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class EventAssigneeTableModelImpl
	extends BaseModelImpl<EventAssigneeTable>
	implements EventAssigneeTableModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a event assignee table model instance should use the <code>EventAssigneeTable</code> interface instead.
	 */
	public static final String TABLE_NAME = "EventAssigneeTable";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"Id", Types.INTEGER},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"eventId", Types.INTEGER},
		{"assigneeId", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("assigneeId", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EventAssigneeTable (uuid_ VARCHAR(75) null,Id INTEGER not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,eventId INTEGER,assigneeId INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table EventAssigneeTable";

	public static final String ORDER_BY_JPQL =
		" ORDER BY eventAssigneeTable.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EventAssigneeTable.Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long ID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EventAssigneeTable toModel(EventAssigneeTableSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EventAssigneeTable model = new EventAssigneeTableImpl();

		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setEventId(soapModel.getEventId());
		model.setAssigneeId(soapModel.getAssigneeId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EventAssigneeTable> toModels(
		EventAssigneeTableSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<EventAssigneeTable> models = new ArrayList<EventAssigneeTable>(
			soapModels.length);

		for (EventAssigneeTableSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EventAssigneeTableModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EventAssigneeTable.class;
	}

	@Override
	public String getModelClassName() {
		return EventAssigneeTable.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EventAssigneeTable, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EventAssigneeTable, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EventAssigneeTable, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EventAssigneeTable)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EventAssigneeTable, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EventAssigneeTable, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EventAssigneeTable)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EventAssigneeTable, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EventAssigneeTable, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EventAssigneeTable>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EventAssigneeTable.class.getClassLoader(), EventAssigneeTable.class,
			ModelWrapper.class);

		try {
			Constructor<EventAssigneeTable> constructor =
				(Constructor<EventAssigneeTable>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<EventAssigneeTable, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EventAssigneeTable, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EventAssigneeTable, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<EventAssigneeTable, Object>>();
		Map<String, BiConsumer<EventAssigneeTable, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<EventAssigneeTable, ?>>();

		attributeGetterFunctions.put("uuid", EventAssigneeTable::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<EventAssigneeTable, String>)
				EventAssigneeTable::setUuid);
		attributeGetterFunctions.put("Id", EventAssigneeTable::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<EventAssigneeTable, Integer>)EventAssigneeTable::setId);
		attributeGetterFunctions.put("groupId", EventAssigneeTable::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EventAssigneeTable, Long>)
				EventAssigneeTable::setGroupId);
		attributeGetterFunctions.put(
			"companyId", EventAssigneeTable::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EventAssigneeTable, Long>)
				EventAssigneeTable::setCompanyId);
		attributeGetterFunctions.put("userId", EventAssigneeTable::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EventAssigneeTable, Long>)
				EventAssigneeTable::setUserId);
		attributeGetterFunctions.put(
			"userName", EventAssigneeTable::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EventAssigneeTable, String>)
				EventAssigneeTable::setUserName);
		attributeGetterFunctions.put(
			"createDate", EventAssigneeTable::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EventAssigneeTable, Date>)
				EventAssigneeTable::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EventAssigneeTable::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EventAssigneeTable, Date>)
				EventAssigneeTable::setModifiedDate);
		attributeGetterFunctions.put("name", EventAssigneeTable::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<EventAssigneeTable, String>)
				EventAssigneeTable::setName);
		attributeGetterFunctions.put("eventId", EventAssigneeTable::getEventId);
		attributeSetterBiConsumers.put(
			"eventId",
			(BiConsumer<EventAssigneeTable, Integer>)
				EventAssigneeTable::setEventId);
		attributeGetterFunctions.put(
			"assigneeId", EventAssigneeTable::getAssigneeId);
		attributeSetterBiConsumers.put(
			"assigneeId",
			(BiConsumer<EventAssigneeTable, Integer>)
				EventAssigneeTable::setAssigneeId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		_Id = Id;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public int getEventId() {
		return _eventId;
	}

	@Override
	public void setEventId(int eventId) {
		_eventId = eventId;
	}

	@JSON
	@Override
	public int getAssigneeId() {
		return _assigneeId;
	}

	@Override
	public void setAssigneeId(int assigneeId) {
		_assigneeId = assigneeId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EventAssigneeTable.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public EventAssigneeTable toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EventAssigneeTable>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EventAssigneeTableImpl eventAssigneeTableImpl =
			new EventAssigneeTableImpl();

		eventAssigneeTableImpl.setUuid(getUuid());
		eventAssigneeTableImpl.setId(getId());
		eventAssigneeTableImpl.setGroupId(getGroupId());
		eventAssigneeTableImpl.setCompanyId(getCompanyId());
		eventAssigneeTableImpl.setUserId(getUserId());
		eventAssigneeTableImpl.setUserName(getUserName());
		eventAssigneeTableImpl.setCreateDate(getCreateDate());
		eventAssigneeTableImpl.setModifiedDate(getModifiedDate());
		eventAssigneeTableImpl.setName(getName());
		eventAssigneeTableImpl.setEventId(getEventId());
		eventAssigneeTableImpl.setAssigneeId(getAssigneeId());

		eventAssigneeTableImpl.resetOriginalValues();

		return eventAssigneeTableImpl;
	}

	@Override
	public int compareTo(EventAssigneeTable eventAssigneeTable) {
		int primaryKey = eventAssigneeTable.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EventAssigneeTable)) {
			return false;
		}

		EventAssigneeTable eventAssigneeTable = (EventAssigneeTable)obj;

		int primaryKey = eventAssigneeTable.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		EventAssigneeTableModelImpl eventAssigneeTableModelImpl = this;

		eventAssigneeTableModelImpl._originalUuid =
			eventAssigneeTableModelImpl._uuid;

		eventAssigneeTableModelImpl._originalGroupId =
			eventAssigneeTableModelImpl._groupId;

		eventAssigneeTableModelImpl._setOriginalGroupId = false;

		eventAssigneeTableModelImpl._originalCompanyId =
			eventAssigneeTableModelImpl._companyId;

		eventAssigneeTableModelImpl._setOriginalCompanyId = false;

		eventAssigneeTableModelImpl._setModifiedDate = false;

		eventAssigneeTableModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EventAssigneeTable> toCacheModel() {
		EventAssigneeTableCacheModel eventAssigneeTableCacheModel =
			new EventAssigneeTableCacheModel();

		eventAssigneeTableCacheModel.uuid = getUuid();

		String uuid = eventAssigneeTableCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			eventAssigneeTableCacheModel.uuid = null;
		}

		eventAssigneeTableCacheModel.Id = getId();

		eventAssigneeTableCacheModel.groupId = getGroupId();

		eventAssigneeTableCacheModel.companyId = getCompanyId();

		eventAssigneeTableCacheModel.userId = getUserId();

		eventAssigneeTableCacheModel.userName = getUserName();

		String userName = eventAssigneeTableCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			eventAssigneeTableCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			eventAssigneeTableCacheModel.createDate = createDate.getTime();
		}
		else {
			eventAssigneeTableCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			eventAssigneeTableCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			eventAssigneeTableCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		eventAssigneeTableCacheModel.name = getName();

		String name = eventAssigneeTableCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			eventAssigneeTableCacheModel.name = null;
		}

		eventAssigneeTableCacheModel.eventId = getEventId();

		eventAssigneeTableCacheModel.assigneeId = getAssigneeId();

		return eventAssigneeTableCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EventAssigneeTable, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EventAssigneeTable, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EventAssigneeTable, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((EventAssigneeTable)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EventAssigneeTable, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EventAssigneeTable, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EventAssigneeTable, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EventAssigneeTable)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EventAssigneeTable>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private int _Id;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private int _eventId;
	private int _assigneeId;
	private long _columnBitmask;
	private EventAssigneeTable _escapedModel;

}