/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model.impl;

import basic.model.profileIntrest;
import basic.model.profileIntrestModel;
import basic.model.profileIntrestSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the profileIntrest service. Represents a row in the &quot;profileIntrest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>profileIntrestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link profileIntrestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see profileIntrestImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class profileIntrestModelImpl
	extends BaseModelImpl<profileIntrest> implements profileIntrestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a profile intrest model instance should use the <code>profileIntrest</code> interface instead.
	 */
	public static final String TABLE_NAME = "profileIntrest";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"Id", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"profileId", Types.BIGINT}, {"intrest", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("profileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("intrest", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table profileIntrest (uuid_ VARCHAR(75) null,Id LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,profileId LONG,intrest VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table profileIntrest";

	public static final String ORDER_BY_JPQL =
		" ORDER BY profileIntrest.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY profileIntrest.Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long ID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static profileIntrest toModel(profileIntrestSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		profileIntrest model = new profileIntrestImpl();

		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setProfileId(soapModel.getProfileId());
		model.setIntrest(soapModel.getIntrest());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<profileIntrest> toModels(
		profileIntrestSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<profileIntrest> models = new ArrayList<profileIntrest>(
			soapModels.length);

		for (profileIntrestSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public profileIntrestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return profileIntrest.class;
	}

	@Override
	public String getModelClassName() {
		return profileIntrest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<profileIntrest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<profileIntrest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<profileIntrest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((profileIntrest)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<profileIntrest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<profileIntrest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(profileIntrest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<profileIntrest, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<profileIntrest, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, profileIntrest>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			profileIntrest.class.getClassLoader(), profileIntrest.class,
			ModelWrapper.class);

		try {
			Constructor<profileIntrest> constructor =
				(Constructor<profileIntrest>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<profileIntrest, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<profileIntrest, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<profileIntrest, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<profileIntrest, Object>>();
		Map<String, BiConsumer<profileIntrest, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<profileIntrest, ?>>();

		attributeGetterFunctions.put("uuid", profileIntrest::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<profileIntrest, String>)profileIntrest::setUuid);
		attributeGetterFunctions.put("Id", profileIntrest::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<profileIntrest, Long>)profileIntrest::setId);
		attributeGetterFunctions.put("groupId", profileIntrest::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<profileIntrest, Long>)profileIntrest::setGroupId);
		attributeGetterFunctions.put("companyId", profileIntrest::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<profileIntrest, Long>)profileIntrest::setCompanyId);
		attributeGetterFunctions.put("userId", profileIntrest::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<profileIntrest, Long>)profileIntrest::setUserId);
		attributeGetterFunctions.put("userName", profileIntrest::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<profileIntrest, String>)profileIntrest::setUserName);
		attributeGetterFunctions.put(
			"createDate", profileIntrest::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<profileIntrest, Date>)profileIntrest::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", profileIntrest::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<profileIntrest, Date>)profileIntrest::setModifiedDate);
		attributeGetterFunctions.put("profileId", profileIntrest::getProfileId);
		attributeSetterBiConsumers.put(
			"profileId",
			(BiConsumer<profileIntrest, Long>)profileIntrest::setProfileId);
		attributeGetterFunctions.put("intrest", profileIntrest::getIntrest);
		attributeSetterBiConsumers.put(
			"intrest",
			(BiConsumer<profileIntrest, String>)profileIntrest::setIntrest);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		_Id = Id;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getProfileId() {
		return _profileId;
	}

	@Override
	public void setProfileId(long profileId) {
		_profileId = profileId;
	}

	@JSON
	@Override
	public String getIntrest() {
		if (_intrest == null) {
			return "";
		}
		else {
			return _intrest;
		}
	}

	@Override
	public void setIntrest(String intrest) {
		_intrest = intrest;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(profileIntrest.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), profileIntrest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public profileIntrest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, profileIntrest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		profileIntrestImpl profileIntrestImpl = new profileIntrestImpl();

		profileIntrestImpl.setUuid(getUuid());
		profileIntrestImpl.setId(getId());
		profileIntrestImpl.setGroupId(getGroupId());
		profileIntrestImpl.setCompanyId(getCompanyId());
		profileIntrestImpl.setUserId(getUserId());
		profileIntrestImpl.setUserName(getUserName());
		profileIntrestImpl.setCreateDate(getCreateDate());
		profileIntrestImpl.setModifiedDate(getModifiedDate());
		profileIntrestImpl.setProfileId(getProfileId());
		profileIntrestImpl.setIntrest(getIntrest());

		profileIntrestImpl.resetOriginalValues();

		return profileIntrestImpl;
	}

	@Override
	public int compareTo(profileIntrest profileIntrest) {
		long primaryKey = profileIntrest.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof profileIntrest)) {
			return false;
		}

		profileIntrest profileIntrest = (profileIntrest)obj;

		long primaryKey = profileIntrest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		profileIntrestModelImpl profileIntrestModelImpl = this;

		profileIntrestModelImpl._originalUuid = profileIntrestModelImpl._uuid;

		profileIntrestModelImpl._originalGroupId =
			profileIntrestModelImpl._groupId;

		profileIntrestModelImpl._setOriginalGroupId = false;

		profileIntrestModelImpl._originalCompanyId =
			profileIntrestModelImpl._companyId;

		profileIntrestModelImpl._setOriginalCompanyId = false;

		profileIntrestModelImpl._setModifiedDate = false;

		profileIntrestModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<profileIntrest> toCacheModel() {
		profileIntrestCacheModel profileIntrestCacheModel =
			new profileIntrestCacheModel();

		profileIntrestCacheModel.uuid = getUuid();

		String uuid = profileIntrestCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			profileIntrestCacheModel.uuid = null;
		}

		profileIntrestCacheModel.Id = getId();

		profileIntrestCacheModel.groupId = getGroupId();

		profileIntrestCacheModel.companyId = getCompanyId();

		profileIntrestCacheModel.userId = getUserId();

		profileIntrestCacheModel.userName = getUserName();

		String userName = profileIntrestCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			profileIntrestCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			profileIntrestCacheModel.createDate = createDate.getTime();
		}
		else {
			profileIntrestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			profileIntrestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			profileIntrestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		profileIntrestCacheModel.profileId = getProfileId();

		profileIntrestCacheModel.intrest = getIntrest();

		String intrest = profileIntrestCacheModel.intrest;

		if ((intrest != null) && (intrest.length() == 0)) {
			profileIntrestCacheModel.intrest = null;
		}

		return profileIntrestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<profileIntrest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<profileIntrest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<profileIntrest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((profileIntrest)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<profileIntrest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<profileIntrest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<profileIntrest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((profileIntrest)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, profileIntrest>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _Id;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _profileId;
	private String _intrest;
	private long _columnBitmask;
	private profileIntrest _escapedModel;

}