/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model.impl;

import basic.model.profileEducation;
import basic.model.profileEducationModel;
import basic.model.profileEducationSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the profileEducation service. Represents a row in the &quot;profileEducation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>profileEducationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link profileEducationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see profileEducationImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class profileEducationModelImpl
	extends BaseModelImpl<profileEducation> implements profileEducationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a profile education model instance should use the <code>profileEducation</code> interface instead.
	 */
	public static final String TABLE_NAME = "profileEducation";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"Id", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"profileId", Types.BIGINT}, {"educationCategory", Types.VARCHAR},
		{"degree", Types.VARCHAR}, {"fieldOfStudy", Types.VARCHAR},
		{"startYear", Types.VARCHAR}, {"endYear", Types.VARCHAR},
		{"grade", Types.VARCHAR}, {"description", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("profileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("educationCategory", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("degree", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fieldOfStudy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startYear", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("endYear", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("grade", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table profileEducation (uuid_ VARCHAR(75) null,Id LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,profileId LONG,educationCategory VARCHAR(75) null,degree VARCHAR(75) null,fieldOfStudy VARCHAR(75) null,startYear VARCHAR(75) null,endYear VARCHAR(75) null,grade VARCHAR(75) null,description VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table profileEducation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY profileEducation.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY profileEducation.Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long ID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static profileEducation toModel(profileEducationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		profileEducation model = new profileEducationImpl();

		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setProfileId(soapModel.getProfileId());
		model.setEducationCategory(soapModel.getEducationCategory());
		model.setDegree(soapModel.getDegree());
		model.setFieldOfStudy(soapModel.getFieldOfStudy());
		model.setStartYear(soapModel.getStartYear());
		model.setEndYear(soapModel.getEndYear());
		model.setGrade(soapModel.getGrade());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<profileEducation> toModels(
		profileEducationSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<profileEducation> models = new ArrayList<profileEducation>(
			soapModels.length);

		for (profileEducationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public profileEducationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return profileEducation.class;
	}

	@Override
	public String getModelClassName() {
		return profileEducation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<profileEducation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<profileEducation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<profileEducation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((profileEducation)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<profileEducation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<profileEducation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(profileEducation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<profileEducation, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<profileEducation, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, profileEducation>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			profileEducation.class.getClassLoader(), profileEducation.class,
			ModelWrapper.class);

		try {
			Constructor<profileEducation> constructor =
				(Constructor<profileEducation>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<profileEducation, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<profileEducation, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<profileEducation, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<profileEducation, Object>>();
		Map<String, BiConsumer<profileEducation, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<profileEducation, ?>>();

		attributeGetterFunctions.put("uuid", profileEducation::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<profileEducation, String>)profileEducation::setUuid);
		attributeGetterFunctions.put("Id", profileEducation::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<profileEducation, Long>)profileEducation::setId);
		attributeGetterFunctions.put("groupId", profileEducation::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<profileEducation, Long>)profileEducation::setGroupId);
		attributeGetterFunctions.put(
			"companyId", profileEducation::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<profileEducation, Long>)profileEducation::setCompanyId);
		attributeGetterFunctions.put("userId", profileEducation::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<profileEducation, Long>)profileEducation::setUserId);
		attributeGetterFunctions.put("userName", profileEducation::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<profileEducation, String>)
				profileEducation::setUserName);
		attributeGetterFunctions.put(
			"createDate", profileEducation::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<profileEducation, Date>)
				profileEducation::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", profileEducation::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<profileEducation, Date>)
				profileEducation::setModifiedDate);
		attributeGetterFunctions.put(
			"profileId", profileEducation::getProfileId);
		attributeSetterBiConsumers.put(
			"profileId",
			(BiConsumer<profileEducation, Long>)profileEducation::setProfileId);
		attributeGetterFunctions.put(
			"educationCategory", profileEducation::getEducationCategory);
		attributeSetterBiConsumers.put(
			"educationCategory",
			(BiConsumer<profileEducation, String>)
				profileEducation::setEducationCategory);
		attributeGetterFunctions.put("degree", profileEducation::getDegree);
		attributeSetterBiConsumers.put(
			"degree",
			(BiConsumer<profileEducation, String>)profileEducation::setDegree);
		attributeGetterFunctions.put(
			"fieldOfStudy", profileEducation::getFieldOfStudy);
		attributeSetterBiConsumers.put(
			"fieldOfStudy",
			(BiConsumer<profileEducation, String>)
				profileEducation::setFieldOfStudy);
		attributeGetterFunctions.put(
			"startYear", profileEducation::getStartYear);
		attributeSetterBiConsumers.put(
			"startYear",
			(BiConsumer<profileEducation, String>)
				profileEducation::setStartYear);
		attributeGetterFunctions.put("endYear", profileEducation::getEndYear);
		attributeSetterBiConsumers.put(
			"endYear",
			(BiConsumer<profileEducation, String>)profileEducation::setEndYear);
		attributeGetterFunctions.put("grade", profileEducation::getGrade);
		attributeSetterBiConsumers.put(
			"grade",
			(BiConsumer<profileEducation, String>)profileEducation::setGrade);
		attributeGetterFunctions.put(
			"description", profileEducation::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<profileEducation, String>)
				profileEducation::setDescription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		_Id = Id;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getProfileId() {
		return _profileId;
	}

	@Override
	public void setProfileId(long profileId) {
		_profileId = profileId;
	}

	@JSON
	@Override
	public String getEducationCategory() {
		if (_educationCategory == null) {
			return "";
		}
		else {
			return _educationCategory;
		}
	}

	@Override
	public void setEducationCategory(String educationCategory) {
		_educationCategory = educationCategory;
	}

	@JSON
	@Override
	public String getDegree() {
		if (_degree == null) {
			return "";
		}
		else {
			return _degree;
		}
	}

	@Override
	public void setDegree(String degree) {
		_degree = degree;
	}

	@JSON
	@Override
	public String getFieldOfStudy() {
		if (_fieldOfStudy == null) {
			return "";
		}
		else {
			return _fieldOfStudy;
		}
	}

	@Override
	public void setFieldOfStudy(String fieldOfStudy) {
		_fieldOfStudy = fieldOfStudy;
	}

	@JSON
	@Override
	public String getStartYear() {
		if (_startYear == null) {
			return "";
		}
		else {
			return _startYear;
		}
	}

	@Override
	public void setStartYear(String startYear) {
		_startYear = startYear;
	}

	@JSON
	@Override
	public String getEndYear() {
		if (_endYear == null) {
			return "";
		}
		else {
			return _endYear;
		}
	}

	@Override
	public void setEndYear(String endYear) {
		_endYear = endYear;
	}

	@JSON
	@Override
	public String getGrade() {
		if (_grade == null) {
			return "";
		}
		else {
			return _grade;
		}
	}

	@Override
	public void setGrade(String grade) {
		_grade = grade;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(profileEducation.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), profileEducation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public profileEducation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, profileEducation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		profileEducationImpl profileEducationImpl = new profileEducationImpl();

		profileEducationImpl.setUuid(getUuid());
		profileEducationImpl.setId(getId());
		profileEducationImpl.setGroupId(getGroupId());
		profileEducationImpl.setCompanyId(getCompanyId());
		profileEducationImpl.setUserId(getUserId());
		profileEducationImpl.setUserName(getUserName());
		profileEducationImpl.setCreateDate(getCreateDate());
		profileEducationImpl.setModifiedDate(getModifiedDate());
		profileEducationImpl.setProfileId(getProfileId());
		profileEducationImpl.setEducationCategory(getEducationCategory());
		profileEducationImpl.setDegree(getDegree());
		profileEducationImpl.setFieldOfStudy(getFieldOfStudy());
		profileEducationImpl.setStartYear(getStartYear());
		profileEducationImpl.setEndYear(getEndYear());
		profileEducationImpl.setGrade(getGrade());
		profileEducationImpl.setDescription(getDescription());

		profileEducationImpl.resetOriginalValues();

		return profileEducationImpl;
	}

	@Override
	public int compareTo(profileEducation profileEducation) {
		long primaryKey = profileEducation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof profileEducation)) {
			return false;
		}

		profileEducation profileEducation = (profileEducation)obj;

		long primaryKey = profileEducation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		profileEducationModelImpl profileEducationModelImpl = this;

		profileEducationModelImpl._originalUuid =
			profileEducationModelImpl._uuid;

		profileEducationModelImpl._originalGroupId =
			profileEducationModelImpl._groupId;

		profileEducationModelImpl._setOriginalGroupId = false;

		profileEducationModelImpl._originalCompanyId =
			profileEducationModelImpl._companyId;

		profileEducationModelImpl._setOriginalCompanyId = false;

		profileEducationModelImpl._setModifiedDate = false;

		profileEducationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<profileEducation> toCacheModel() {
		profileEducationCacheModel profileEducationCacheModel =
			new profileEducationCacheModel();

		profileEducationCacheModel.uuid = getUuid();

		String uuid = profileEducationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			profileEducationCacheModel.uuid = null;
		}

		profileEducationCacheModel.Id = getId();

		profileEducationCacheModel.groupId = getGroupId();

		profileEducationCacheModel.companyId = getCompanyId();

		profileEducationCacheModel.userId = getUserId();

		profileEducationCacheModel.userName = getUserName();

		String userName = profileEducationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			profileEducationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			profileEducationCacheModel.createDate = createDate.getTime();
		}
		else {
			profileEducationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			profileEducationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			profileEducationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		profileEducationCacheModel.profileId = getProfileId();

		profileEducationCacheModel.educationCategory = getEducationCategory();

		String educationCategory = profileEducationCacheModel.educationCategory;

		if ((educationCategory != null) && (educationCategory.length() == 0)) {
			profileEducationCacheModel.educationCategory = null;
		}

		profileEducationCacheModel.degree = getDegree();

		String degree = profileEducationCacheModel.degree;

		if ((degree != null) && (degree.length() == 0)) {
			profileEducationCacheModel.degree = null;
		}

		profileEducationCacheModel.fieldOfStudy = getFieldOfStudy();

		String fieldOfStudy = profileEducationCacheModel.fieldOfStudy;

		if ((fieldOfStudy != null) && (fieldOfStudy.length() == 0)) {
			profileEducationCacheModel.fieldOfStudy = null;
		}

		profileEducationCacheModel.startYear = getStartYear();

		String startYear = profileEducationCacheModel.startYear;

		if ((startYear != null) && (startYear.length() == 0)) {
			profileEducationCacheModel.startYear = null;
		}

		profileEducationCacheModel.endYear = getEndYear();

		String endYear = profileEducationCacheModel.endYear;

		if ((endYear != null) && (endYear.length() == 0)) {
			profileEducationCacheModel.endYear = null;
		}

		profileEducationCacheModel.grade = getGrade();

		String grade = profileEducationCacheModel.grade;

		if ((grade != null) && (grade.length() == 0)) {
			profileEducationCacheModel.grade = null;
		}

		profileEducationCacheModel.description = getDescription();

		String description = profileEducationCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			profileEducationCacheModel.description = null;
		}

		return profileEducationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<profileEducation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<profileEducation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<profileEducation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((profileEducation)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<profileEducation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<profileEducation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<profileEducation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((profileEducation)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, profileEducation>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _Id;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _profileId;
	private String _educationCategory;
	private String _degree;
	private String _fieldOfStudy;
	private String _startYear;
	private String _endYear;
	private String _grade;
	private String _description;
	private long _columnBitmask;
	private profileEducation _escapedModel;

}