/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model.impl;

import basic.model.profileLicensesCertifications;
import basic.model.profileLicensesCertificationsModel;
import basic.model.profileLicensesCertificationsSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the profileLicensesCertifications service. Represents a row in the &quot;profileLicensesCertifications&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>profileLicensesCertificationsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link profileLicensesCertificationsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see profileLicensesCertificationsImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class profileLicensesCertificationsModelImpl
	extends BaseModelImpl<profileLicensesCertifications>
	implements profileLicensesCertificationsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a profile licenses certifications model instance should use the <code>profileLicensesCertifications</code> interface instead.
	 */
	public static final String TABLE_NAME = "profileLicensesCertifications";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"Id", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"profileId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"issuingOrganization", Types.VARCHAR}, {"issueDate", Types.TIMESTAMP},
		{"expirationDate", Types.TIMESTAMP}, {"credentialID", Types.BIGINT},
		{"credentialURL", Types.VARCHAR}, {"notExpire", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("profileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("issuingOrganization", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("issueDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("credentialID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("credentialURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("notExpire", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table profileLicensesCertifications (uuid_ VARCHAR(75) null,Id LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,profileId LONG,name VARCHAR(75) null,issuingOrganization VARCHAR(75) null,issueDate DATE null,expirationDate DATE null,credentialID LONG,credentialURL VARCHAR(75) null,notExpire BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table profileLicensesCertifications";

	public static final String ORDER_BY_JPQL =
		" ORDER BY profileLicensesCertifications.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY profileLicensesCertifications.Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long ID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static profileLicensesCertifications toModel(
		profileLicensesCertificationsSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		profileLicensesCertifications model =
			new profileLicensesCertificationsImpl();

		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setProfileId(soapModel.getProfileId());
		model.setName(soapModel.getName());
		model.setIssuingOrganization(soapModel.getIssuingOrganization());
		model.setIssueDate(soapModel.getIssueDate());
		model.setExpirationDate(soapModel.getExpirationDate());
		model.setCredentialID(soapModel.getCredentialID());
		model.setCredentialURL(soapModel.getCredentialURL());
		model.setNotExpire(soapModel.isNotExpire());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<profileLicensesCertifications> toModels(
		profileLicensesCertificationsSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<profileLicensesCertifications> models =
			new ArrayList<profileLicensesCertifications>(soapModels.length);

		for (profileLicensesCertificationsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public profileLicensesCertificationsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return profileLicensesCertifications.class;
	}

	@Override
	public String getModelClassName() {
		return profileLicensesCertifications.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<profileLicensesCertifications, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<profileLicensesCertifications, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<profileLicensesCertifications, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(profileLicensesCertifications)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<profileLicensesCertifications, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<profileLicensesCertifications, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(profileLicensesCertifications)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<profileLicensesCertifications, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<profileLicensesCertifications, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, profileLicensesCertifications>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			profileLicensesCertifications.class.getClassLoader(),
			profileLicensesCertifications.class, ModelWrapper.class);

		try {
			Constructor<profileLicensesCertifications> constructor =
				(Constructor<profileLicensesCertifications>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map
		<String, Function<profileLicensesCertifications, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<profileLicensesCertifications, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<profileLicensesCertifications, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<profileLicensesCertifications, Object>>();
		Map<String, BiConsumer<profileLicensesCertifications, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<profileLicensesCertifications, ?>>();

		attributeGetterFunctions.put(
			"uuid", profileLicensesCertifications::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<profileLicensesCertifications, String>)
				profileLicensesCertifications::setUuid);
		attributeGetterFunctions.put(
			"Id", profileLicensesCertifications::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<profileLicensesCertifications, Long>)
				profileLicensesCertifications::setId);
		attributeGetterFunctions.put(
			"groupId", profileLicensesCertifications::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<profileLicensesCertifications, Long>)
				profileLicensesCertifications::setGroupId);
		attributeGetterFunctions.put(
			"companyId", profileLicensesCertifications::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<profileLicensesCertifications, Long>)
				profileLicensesCertifications::setCompanyId);
		attributeGetterFunctions.put(
			"userId", profileLicensesCertifications::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<profileLicensesCertifications, Long>)
				profileLicensesCertifications::setUserId);
		attributeGetterFunctions.put(
			"userName", profileLicensesCertifications::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<profileLicensesCertifications, String>)
				profileLicensesCertifications::setUserName);
		attributeGetterFunctions.put(
			"createDate", profileLicensesCertifications::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<profileLicensesCertifications, Date>)
				profileLicensesCertifications::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", profileLicensesCertifications::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<profileLicensesCertifications, Date>)
				profileLicensesCertifications::setModifiedDate);
		attributeGetterFunctions.put(
			"profileId", profileLicensesCertifications::getProfileId);
		attributeSetterBiConsumers.put(
			"profileId",
			(BiConsumer<profileLicensesCertifications, Long>)
				profileLicensesCertifications::setProfileId);
		attributeGetterFunctions.put(
			"name", profileLicensesCertifications::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<profileLicensesCertifications, String>)
				profileLicensesCertifications::setName);
		attributeGetterFunctions.put(
			"issuingOrganization",
			profileLicensesCertifications::getIssuingOrganization);
		attributeSetterBiConsumers.put(
			"issuingOrganization",
			(BiConsumer<profileLicensesCertifications, String>)
				profileLicensesCertifications::setIssuingOrganization);
		attributeGetterFunctions.put(
			"issueDate", profileLicensesCertifications::getIssueDate);
		attributeSetterBiConsumers.put(
			"issueDate",
			(BiConsumer<profileLicensesCertifications, Date>)
				profileLicensesCertifications::setIssueDate);
		attributeGetterFunctions.put(
			"expirationDate", profileLicensesCertifications::getExpirationDate);
		attributeSetterBiConsumers.put(
			"expirationDate",
			(BiConsumer<profileLicensesCertifications, Date>)
				profileLicensesCertifications::setExpirationDate);
		attributeGetterFunctions.put(
			"credentialID", profileLicensesCertifications::getCredentialID);
		attributeSetterBiConsumers.put(
			"credentialID",
			(BiConsumer<profileLicensesCertifications, Long>)
				profileLicensesCertifications::setCredentialID);
		attributeGetterFunctions.put(
			"credentialURL", profileLicensesCertifications::getCredentialURL);
		attributeSetterBiConsumers.put(
			"credentialURL",
			(BiConsumer<profileLicensesCertifications, String>)
				profileLicensesCertifications::setCredentialURL);
		attributeGetterFunctions.put(
			"notExpire", profileLicensesCertifications::getNotExpire);
		attributeSetterBiConsumers.put(
			"notExpire",
			(BiConsumer<profileLicensesCertifications, Boolean>)
				profileLicensesCertifications::setNotExpire);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		_Id = Id;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getProfileId() {
		return _profileId;
	}

	@Override
	public void setProfileId(long profileId) {
		_profileId = profileId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getIssuingOrganization() {
		if (_issuingOrganization == null) {
			return "";
		}
		else {
			return _issuingOrganization;
		}
	}

	@Override
	public void setIssuingOrganization(String issuingOrganization) {
		_issuingOrganization = issuingOrganization;
	}

	@JSON
	@Override
	public Date getIssueDate() {
		return _issueDate;
	}

	@Override
	public void setIssueDate(Date issueDate) {
		_issueDate = issueDate;
	}

	@JSON
	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		_expirationDate = expirationDate;
	}

	@JSON
	@Override
	public long getCredentialID() {
		return _credentialID;
	}

	@Override
	public void setCredentialID(long credentialID) {
		_credentialID = credentialID;
	}

	@JSON
	@Override
	public String getCredentialURL() {
		if (_credentialURL == null) {
			return "";
		}
		else {
			return _credentialURL;
		}
	}

	@Override
	public void setCredentialURL(String credentialURL) {
		_credentialURL = credentialURL;
	}

	@JSON
	@Override
	public boolean getNotExpire() {
		return _notExpire;
	}

	@JSON
	@Override
	public boolean isNotExpire() {
		return _notExpire;
	}

	@Override
	public void setNotExpire(boolean notExpire) {
		_notExpire = notExpire;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				profileLicensesCertifications.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), profileLicensesCertifications.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public profileLicensesCertifications toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, profileLicensesCertifications>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		profileLicensesCertificationsImpl profileLicensesCertificationsImpl =
			new profileLicensesCertificationsImpl();

		profileLicensesCertificationsImpl.setUuid(getUuid());
		profileLicensesCertificationsImpl.setId(getId());
		profileLicensesCertificationsImpl.setGroupId(getGroupId());
		profileLicensesCertificationsImpl.setCompanyId(getCompanyId());
		profileLicensesCertificationsImpl.setUserId(getUserId());
		profileLicensesCertificationsImpl.setUserName(getUserName());
		profileLicensesCertificationsImpl.setCreateDate(getCreateDate());
		profileLicensesCertificationsImpl.setModifiedDate(getModifiedDate());
		profileLicensesCertificationsImpl.setProfileId(getProfileId());
		profileLicensesCertificationsImpl.setName(getName());
		profileLicensesCertificationsImpl.setIssuingOrganization(
			getIssuingOrganization());
		profileLicensesCertificationsImpl.setIssueDate(getIssueDate());
		profileLicensesCertificationsImpl.setExpirationDate(
			getExpirationDate());
		profileLicensesCertificationsImpl.setCredentialID(getCredentialID());
		profileLicensesCertificationsImpl.setCredentialURL(getCredentialURL());
		profileLicensesCertificationsImpl.setNotExpire(isNotExpire());

		profileLicensesCertificationsImpl.resetOriginalValues();

		return profileLicensesCertificationsImpl;
	}

	@Override
	public int compareTo(
		profileLicensesCertifications profileLicensesCertifications) {

		long primaryKey = profileLicensesCertifications.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof profileLicensesCertifications)) {
			return false;
		}

		profileLicensesCertifications profileLicensesCertifications =
			(profileLicensesCertifications)obj;

		long primaryKey = profileLicensesCertifications.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		profileLicensesCertificationsModelImpl
			profileLicensesCertificationsModelImpl = this;

		profileLicensesCertificationsModelImpl._originalUuid =
			profileLicensesCertificationsModelImpl._uuid;

		profileLicensesCertificationsModelImpl._originalGroupId =
			profileLicensesCertificationsModelImpl._groupId;

		profileLicensesCertificationsModelImpl._setOriginalGroupId = false;

		profileLicensesCertificationsModelImpl._originalCompanyId =
			profileLicensesCertificationsModelImpl._companyId;

		profileLicensesCertificationsModelImpl._setOriginalCompanyId = false;

		profileLicensesCertificationsModelImpl._setModifiedDate = false;

		profileLicensesCertificationsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<profileLicensesCertifications> toCacheModel() {
		profileLicensesCertificationsCacheModel
			profileLicensesCertificationsCacheModel =
				new profileLicensesCertificationsCacheModel();

		profileLicensesCertificationsCacheModel.uuid = getUuid();

		String uuid = profileLicensesCertificationsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			profileLicensesCertificationsCacheModel.uuid = null;
		}

		profileLicensesCertificationsCacheModel.Id = getId();

		profileLicensesCertificationsCacheModel.groupId = getGroupId();

		profileLicensesCertificationsCacheModel.companyId = getCompanyId();

		profileLicensesCertificationsCacheModel.userId = getUserId();

		profileLicensesCertificationsCacheModel.userName = getUserName();

		String userName = profileLicensesCertificationsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			profileLicensesCertificationsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			profileLicensesCertificationsCacheModel.createDate =
				createDate.getTime();
		}
		else {
			profileLicensesCertificationsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			profileLicensesCertificationsCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			profileLicensesCertificationsCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		profileLicensesCertificationsCacheModel.profileId = getProfileId();

		profileLicensesCertificationsCacheModel.name = getName();

		String name = profileLicensesCertificationsCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			profileLicensesCertificationsCacheModel.name = null;
		}

		profileLicensesCertificationsCacheModel.issuingOrganization =
			getIssuingOrganization();

		String issuingOrganization =
			profileLicensesCertificationsCacheModel.issuingOrganization;

		if ((issuingOrganization != null) &&
			(issuingOrganization.length() == 0)) {

			profileLicensesCertificationsCacheModel.issuingOrganization = null;
		}

		Date issueDate = getIssueDate();

		if (issueDate != null) {
			profileLicensesCertificationsCacheModel.issueDate =
				issueDate.getTime();
		}
		else {
			profileLicensesCertificationsCacheModel.issueDate = Long.MIN_VALUE;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			profileLicensesCertificationsCacheModel.expirationDate =
				expirationDate.getTime();
		}
		else {
			profileLicensesCertificationsCacheModel.expirationDate =
				Long.MIN_VALUE;
		}

		profileLicensesCertificationsCacheModel.credentialID =
			getCredentialID();

		profileLicensesCertificationsCacheModel.credentialURL =
			getCredentialURL();

		String credentialURL =
			profileLicensesCertificationsCacheModel.credentialURL;

		if ((credentialURL != null) && (credentialURL.length() == 0)) {
			profileLicensesCertificationsCacheModel.credentialURL = null;
		}

		profileLicensesCertificationsCacheModel.notExpire = isNotExpire();

		return profileLicensesCertificationsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<profileLicensesCertifications, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<profileLicensesCertifications, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<profileLicensesCertifications, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply(
					(profileLicensesCertifications)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<profileLicensesCertifications, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<profileLicensesCertifications, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<profileLicensesCertifications, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(profileLicensesCertifications)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, profileLicensesCertifications>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _Id;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _profileId;
	private String _name;
	private String _issuingOrganization;
	private Date _issueDate;
	private Date _expirationDate;
	private long _credentialID;
	private String _credentialURL;
	private boolean _notExpire;
	private long _columnBitmask;
	private profileLicensesCertifications _escapedModel;

}