/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EventAssigneeTable service. Represents a row in the &quot;EventAssigneeTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>basic.model.impl.EventAssigneeTableModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>basic.model.impl.EventAssigneeTableImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EventAssigneeTable
 * @generated
 */
@ProviderType
public interface EventAssigneeTableModel
	extends BaseModel<EventAssigneeTable>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a event assignee table model instance should use the {@link EventAssigneeTable} interface instead.
	 */

	/**
	 * Returns the primary key of this event assignee table.
	 *
	 * @return the primary key of this event assignee table
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this event assignee table.
	 *
	 * @param primaryKey the primary key of this event assignee table
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the uuid of this event assignee table.
	 *
	 * @return the uuid of this event assignee table
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this event assignee table.
	 *
	 * @param uuid the uuid of this event assignee table
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this event assignee table.
	 *
	 * @return the ID of this event assignee table
	 */
	public int getId();

	/**
	 * Sets the ID of this event assignee table.
	 *
	 * @param Id the ID of this event assignee table
	 */
	public void setId(int Id);

	/**
	 * Returns the group ID of this event assignee table.
	 *
	 * @return the group ID of this event assignee table
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this event assignee table.
	 *
	 * @param groupId the group ID of this event assignee table
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this event assignee table.
	 *
	 * @return the company ID of this event assignee table
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this event assignee table.
	 *
	 * @param companyId the company ID of this event assignee table
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this event assignee table.
	 *
	 * @return the user ID of this event assignee table
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this event assignee table.
	 *
	 * @param userId the user ID of this event assignee table
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this event assignee table.
	 *
	 * @return the user uuid of this event assignee table
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this event assignee table.
	 *
	 * @param userUuid the user uuid of this event assignee table
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this event assignee table.
	 *
	 * @return the user name of this event assignee table
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this event assignee table.
	 *
	 * @param userName the user name of this event assignee table
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this event assignee table.
	 *
	 * @return the create date of this event assignee table
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this event assignee table.
	 *
	 * @param createDate the create date of this event assignee table
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this event assignee table.
	 *
	 * @return the modified date of this event assignee table
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this event assignee table.
	 *
	 * @param modifiedDate the modified date of this event assignee table
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this event assignee table.
	 *
	 * @return the name of this event assignee table
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this event assignee table.
	 *
	 * @param name the name of this event assignee table
	 */
	public void setName(String name);

	/**
	 * Returns the event ID of this event assignee table.
	 *
	 * @return the event ID of this event assignee table
	 */
	public int getEventId();

	/**
	 * Sets the event ID of this event assignee table.
	 *
	 * @param eventId the event ID of this event assignee table
	 */
	public void setEventId(int eventId);

	/**
	 * Returns the assignee ID of this event assignee table.
	 *
	 * @return the assignee ID of this event assignee table
	 */
	public int getAssigneeId();

	/**
	 * Sets the assignee ID of this event assignee table.
	 *
	 * @param assigneeId the assignee ID of this event assignee table
	 */
	public void setAssigneeId(int assigneeId);

}