/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EventAttributes service. Represents a row in the &quot;EventAttributes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>basic.model.impl.EventAttributesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>basic.model.impl.EventAttributesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EventAttributes
 * @generated
 */
@ProviderType
public interface EventAttributesModel extends BaseModel<EventAttributes> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a event attributes model instance should use the {@link EventAttributes} interface instead.
	 */

	/**
	 * Returns the primary key of this event attributes.
	 *
	 * @return the primary key of this event attributes
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this event attributes.
	 *
	 * @param primaryKey the primary key of this event attributes
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this event attributes.
	 *
	 * @return the ID of this event attributes
	 */
	public long getId();

	/**
	 * Sets the ID of this event attributes.
	 *
	 * @param id the ID of this event attributes
	 */
	public void setId(long id);

	/**
	 * Returns the attribute number of this event attributes.
	 *
	 * @return the attribute number of this event attributes
	 */
	@AutoEscape
	public String getAttributeNumber();

	/**
	 * Sets the attribute number of this event attributes.
	 *
	 * @param attributeNumber the attribute number of this event attributes
	 */
	public void setAttributeNumber(String attributeNumber);

	/**
	 * Returns the attribute name of this event attributes.
	 *
	 * @return the attribute name of this event attributes
	 */
	@AutoEscape
	public String getAttributeName();

	/**
	 * Sets the attribute name of this event attributes.
	 *
	 * @param attributeName the attribute name of this event attributes
	 */
	public void setAttributeName(String attributeName);

	/**
	 * Returns the event ID of this event attributes.
	 *
	 * @return the event ID of this event attributes
	 */
	@AutoEscape
	public String getEventId();

	/**
	 * Sets the event ID of this event attributes.
	 *
	 * @param eventId the event ID of this event attributes
	 */
	public void setEventId(String eventId);

}