/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the profileEducation service. Represents a row in the &quot;profileEducation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>basic.model.impl.profileEducationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>basic.model.impl.profileEducationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see profileEducation
 * @generated
 */
@ProviderType
public interface profileEducationModel
	extends BaseModel<profileEducation>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profile education model instance should use the {@link profileEducation} interface instead.
	 */

	/**
	 * Returns the primary key of this profile education.
	 *
	 * @return the primary key of this profile education
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this profile education.
	 *
	 * @param primaryKey the primary key of this profile education
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this profile education.
	 *
	 * @return the uuid of this profile education
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this profile education.
	 *
	 * @param uuid the uuid of this profile education
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this profile education.
	 *
	 * @return the ID of this profile education
	 */
	public long getId();

	/**
	 * Sets the ID of this profile education.
	 *
	 * @param Id the ID of this profile education
	 */
	public void setId(long Id);

	/**
	 * Returns the group ID of this profile education.
	 *
	 * @return the group ID of this profile education
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this profile education.
	 *
	 * @param groupId the group ID of this profile education
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this profile education.
	 *
	 * @return the company ID of this profile education
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this profile education.
	 *
	 * @param companyId the company ID of this profile education
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this profile education.
	 *
	 * @return the user ID of this profile education
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this profile education.
	 *
	 * @param userId the user ID of this profile education
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this profile education.
	 *
	 * @return the user uuid of this profile education
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this profile education.
	 *
	 * @param userUuid the user uuid of this profile education
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this profile education.
	 *
	 * @return the user name of this profile education
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this profile education.
	 *
	 * @param userName the user name of this profile education
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this profile education.
	 *
	 * @return the create date of this profile education
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this profile education.
	 *
	 * @param createDate the create date of this profile education
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this profile education.
	 *
	 * @return the modified date of this profile education
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this profile education.
	 *
	 * @param modifiedDate the modified date of this profile education
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the profile ID of this profile education.
	 *
	 * @return the profile ID of this profile education
	 */
	public long getProfileId();

	/**
	 * Sets the profile ID of this profile education.
	 *
	 * @param profileId the profile ID of this profile education
	 */
	public void setProfileId(long profileId);

	/**
	 * Returns the education category of this profile education.
	 *
	 * @return the education category of this profile education
	 */
	@AutoEscape
	public String getEducationCategory();

	/**
	 * Sets the education category of this profile education.
	 *
	 * @param educationCategory the education category of this profile education
	 */
	public void setEducationCategory(String educationCategory);

	/**
	 * Returns the degree of this profile education.
	 *
	 * @return the degree of this profile education
	 */
	@AutoEscape
	public String getDegree();

	/**
	 * Sets the degree of this profile education.
	 *
	 * @param degree the degree of this profile education
	 */
	public void setDegree(String degree);

	/**
	 * Returns the field of study of this profile education.
	 *
	 * @return the field of study of this profile education
	 */
	@AutoEscape
	public String getFieldOfStudy();

	/**
	 * Sets the field of study of this profile education.
	 *
	 * @param fieldOfStudy the field of study of this profile education
	 */
	public void setFieldOfStudy(String fieldOfStudy);

	/**
	 * Returns the start year of this profile education.
	 *
	 * @return the start year of this profile education
	 */
	@AutoEscape
	public String getStartYear();

	/**
	 * Sets the start year of this profile education.
	 *
	 * @param startYear the start year of this profile education
	 */
	public void setStartYear(String startYear);

	/**
	 * Returns the end year of this profile education.
	 *
	 * @return the end year of this profile education
	 */
	@AutoEscape
	public String getEndYear();

	/**
	 * Sets the end year of this profile education.
	 *
	 * @param endYear the end year of this profile education
	 */
	public void setEndYear(String endYear);

	/**
	 * Returns the grade of this profile education.
	 *
	 * @return the grade of this profile education
	 */
	@AutoEscape
	public String getGrade();

	/**
	 * Sets the grade of this profile education.
	 *
	 * @param grade the grade of this profile education
	 */
	public void setGrade(String grade);

	/**
	 * Returns the description of this profile education.
	 *
	 * @return the description of this profile education
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this profile education.
	 *
	 * @param description the description of this profile education
	 */
	public void setDescription(String description);

}