/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProfileTestimonial service. Represents a row in the &quot;ProfileTestimonial&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>basic.model.impl.ProfileTestimonialModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>basic.model.impl.ProfileTestimonialImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProfileTestimonial
 * @generated
 */
@ProviderType
public interface ProfileTestimonialModel
	extends BaseModel<ProfileTestimonial>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profile testimonial model instance should use the {@link ProfileTestimonial} interface instead.
	 */

	/**
	 * Returns the primary key of this profile testimonial.
	 *
	 * @return the primary key of this profile testimonial
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this profile testimonial.
	 *
	 * @param primaryKey the primary key of this profile testimonial
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this profile testimonial.
	 *
	 * @return the uuid of this profile testimonial
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this profile testimonial.
	 *
	 * @param uuid the uuid of this profile testimonial
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this profile testimonial.
	 *
	 * @return the ID of this profile testimonial
	 */
	public long getId();

	/**
	 * Sets the ID of this profile testimonial.
	 *
	 * @param id the ID of this profile testimonial
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this profile testimonial.
	 *
	 * @return the group ID of this profile testimonial
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this profile testimonial.
	 *
	 * @param groupId the group ID of this profile testimonial
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this profile testimonial.
	 *
	 * @return the company ID of this profile testimonial
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this profile testimonial.
	 *
	 * @param companyId the company ID of this profile testimonial
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this profile testimonial.
	 *
	 * @return the user ID of this profile testimonial
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this profile testimonial.
	 *
	 * @param userId the user ID of this profile testimonial
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this profile testimonial.
	 *
	 * @return the user uuid of this profile testimonial
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this profile testimonial.
	 *
	 * @param userUuid the user uuid of this profile testimonial
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this profile testimonial.
	 *
	 * @return the user name of this profile testimonial
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this profile testimonial.
	 *
	 * @param userName the user name of this profile testimonial
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this profile testimonial.
	 *
	 * @return the create date of this profile testimonial
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this profile testimonial.
	 *
	 * @param createDate the create date of this profile testimonial
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this profile testimonial.
	 *
	 * @return the modified date of this profile testimonial
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this profile testimonial.
	 *
	 * @param modifiedDate the modified date of this profile testimonial
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the testimonialprovidername of this profile testimonial.
	 *
	 * @return the testimonialprovidername of this profile testimonial
	 */
	@AutoEscape
	public String getTestimonialprovidername();

	/**
	 * Sets the testimonialprovidername of this profile testimonial.
	 *
	 * @param testimonialprovidername the testimonialprovidername of this profile testimonial
	 */
	public void setTestimonialprovidername(String testimonialprovidername);

	/**
	 * Returns the testimonialprovideremail of this profile testimonial.
	 *
	 * @return the testimonialprovideremail of this profile testimonial
	 */
	@AutoEscape
	public String getTestimonialprovideremail();

	/**
	 * Sets the testimonialprovideremail of this profile testimonial.
	 *
	 * @param testimonialprovideremail the testimonialprovideremail of this profile testimonial
	 */
	public void setTestimonialprovideremail(String testimonialprovideremail);

	/**
	 * Returns the testimonialprovorgname of this profile testimonial.
	 *
	 * @return the testimonialprovorgname of this profile testimonial
	 */
	@AutoEscape
	public String getTestimonialprovorgname();

	/**
	 * Sets the testimonialprovorgname of this profile testimonial.
	 *
	 * @param testimonialprovorgname the testimonialprovorgname of this profile testimonial
	 */
	public void setTestimonialprovorgname(String testimonialprovorgname);

	/**
	 * Returns the testimonialprovidertitle of this profile testimonial.
	 *
	 * @return the testimonialprovidertitle of this profile testimonial
	 */
	@AutoEscape
	public String getTestimonialprovidertitle();

	/**
	 * Sets the testimonialprovidertitle of this profile testimonial.
	 *
	 * @param testimonialprovidertitle the testimonialprovidertitle of this profile testimonial
	 */
	public void setTestimonialprovidertitle(String testimonialprovidertitle);

	/**
	 * Returns the testimonialprivatemessage of this profile testimonial.
	 *
	 * @return the testimonialprivatemessage of this profile testimonial
	 */
	@AutoEscape
	public String getTestimonialprivatemessage();

	/**
	 * Sets the testimonialprivatemessage of this profile testimonial.
	 *
	 * @param testimonialprivatemessage the testimonialprivatemessage of this profile testimonial
	 */
	public void setTestimonialprivatemessage(String testimonialprivatemessage);

	/**
	 * Returns the image preview of this profile testimonial.
	 *
	 * @return the image preview of this profile testimonial
	 */
	@AutoEscape
	public String getImagePreview();

	/**
	 * Sets the image preview of this profile testimonial.
	 *
	 * @param imagePreview the image preview of this profile testimonial
	 */
	public void setImagePreview(String imagePreview);

}