/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the profileLicensesCertifications service. Represents a row in the &quot;profileLicensesCertifications&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>basic.model.impl.profileLicensesCertificationsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>basic.model.impl.profileLicensesCertificationsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see profileLicensesCertifications
 * @generated
 */
@ProviderType
public interface profileLicensesCertificationsModel
	extends BaseModel<profileLicensesCertifications>, GroupedModel,
			ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profile licenses certifications model instance should use the {@link profileLicensesCertifications} interface instead.
	 */

	/**
	 * Returns the primary key of this profile licenses certifications.
	 *
	 * @return the primary key of this profile licenses certifications
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this profile licenses certifications.
	 *
	 * @param primaryKey the primary key of this profile licenses certifications
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this profile licenses certifications.
	 *
	 * @return the uuid of this profile licenses certifications
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this profile licenses certifications.
	 *
	 * @param uuid the uuid of this profile licenses certifications
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this profile licenses certifications.
	 *
	 * @return the ID of this profile licenses certifications
	 */
	public long getId();

	/**
	 * Sets the ID of this profile licenses certifications.
	 *
	 * @param Id the ID of this profile licenses certifications
	 */
	public void setId(long Id);

	/**
	 * Returns the group ID of this profile licenses certifications.
	 *
	 * @return the group ID of this profile licenses certifications
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this profile licenses certifications.
	 *
	 * @param groupId the group ID of this profile licenses certifications
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this profile licenses certifications.
	 *
	 * @return the company ID of this profile licenses certifications
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this profile licenses certifications.
	 *
	 * @param companyId the company ID of this profile licenses certifications
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this profile licenses certifications.
	 *
	 * @return the user ID of this profile licenses certifications
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this profile licenses certifications.
	 *
	 * @param userId the user ID of this profile licenses certifications
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this profile licenses certifications.
	 *
	 * @return the user uuid of this profile licenses certifications
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this profile licenses certifications.
	 *
	 * @param userUuid the user uuid of this profile licenses certifications
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this profile licenses certifications.
	 *
	 * @return the user name of this profile licenses certifications
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this profile licenses certifications.
	 *
	 * @param userName the user name of this profile licenses certifications
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this profile licenses certifications.
	 *
	 * @return the create date of this profile licenses certifications
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this profile licenses certifications.
	 *
	 * @param createDate the create date of this profile licenses certifications
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this profile licenses certifications.
	 *
	 * @return the modified date of this profile licenses certifications
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this profile licenses certifications.
	 *
	 * @param modifiedDate the modified date of this profile licenses certifications
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the profile ID of this profile licenses certifications.
	 *
	 * @return the profile ID of this profile licenses certifications
	 */
	public long getProfileId();

	/**
	 * Sets the profile ID of this profile licenses certifications.
	 *
	 * @param profileId the profile ID of this profile licenses certifications
	 */
	public void setProfileId(long profileId);

	/**
	 * Returns the name of this profile licenses certifications.
	 *
	 * @return the name of this profile licenses certifications
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this profile licenses certifications.
	 *
	 * @param name the name of this profile licenses certifications
	 */
	public void setName(String name);

	/**
	 * Returns the issuing organization of this profile licenses certifications.
	 *
	 * @return the issuing organization of this profile licenses certifications
	 */
	@AutoEscape
	public String getIssuingOrganization();

	/**
	 * Sets the issuing organization of this profile licenses certifications.
	 *
	 * @param issuingOrganization the issuing organization of this profile licenses certifications
	 */
	public void setIssuingOrganization(String issuingOrganization);

	/**
	 * Returns the issue date of this profile licenses certifications.
	 *
	 * @return the issue date of this profile licenses certifications
	 */
	public Date getIssueDate();

	/**
	 * Sets the issue date of this profile licenses certifications.
	 *
	 * @param issueDate the issue date of this profile licenses certifications
	 */
	public void setIssueDate(Date issueDate);

	/**
	 * Returns the expiration date of this profile licenses certifications.
	 *
	 * @return the expiration date of this profile licenses certifications
	 */
	public Date getExpirationDate();

	/**
	 * Sets the expiration date of this profile licenses certifications.
	 *
	 * @param expirationDate the expiration date of this profile licenses certifications
	 */
	public void setExpirationDate(Date expirationDate);

	/**
	 * Returns the credential ID of this profile licenses certifications.
	 *
	 * @return the credential ID of this profile licenses certifications
	 */
	public long getCredentialID();

	/**
	 * Sets the credential ID of this profile licenses certifications.
	 *
	 * @param credentialID the credential ID of this profile licenses certifications
	 */
	public void setCredentialID(long credentialID);

	/**
	 * Returns the credential url of this profile licenses certifications.
	 *
	 * @return the credential url of this profile licenses certifications
	 */
	@AutoEscape
	public String getCredentialURL();

	/**
	 * Sets the credential url of this profile licenses certifications.
	 *
	 * @param credentialURL the credential url of this profile licenses certifications
	 */
	public void setCredentialURL(String credentialURL);

	/**
	 * Returns the not expire of this profile licenses certifications.
	 *
	 * @return the not expire of this profile licenses certifications
	 */
	public boolean getNotExpire();

	/**
	 * Returns <code>true</code> if this profile licenses certifications is not expire.
	 *
	 * @return <code>true</code> if this profile licenses certifications is not expire; <code>false</code> otherwise
	 */
	public boolean isNotExpire();

	/**
	 * Sets whether this profile licenses certifications is not expire.
	 *
	 * @param notExpire the not expire of this profile licenses certifications
	 */
	public void setNotExpire(boolean notExpire);

}