/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package basic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the profileWorkExperience service. Represents a row in the &quot;profileWorkExperience&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>basic.model.impl.profileWorkExperienceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>basic.model.impl.profileWorkExperienceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see profileWorkExperience
 * @generated
 */
@ProviderType
public interface profileWorkExperienceModel
	extends BaseModel<profileWorkExperience>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profile work experience model instance should use the {@link profileWorkExperience} interface instead.
	 */

	/**
	 * Returns the primary key of this profile work experience.
	 *
	 * @return the primary key of this profile work experience
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this profile work experience.
	 *
	 * @param primaryKey the primary key of this profile work experience
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this profile work experience.
	 *
	 * @return the uuid of this profile work experience
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this profile work experience.
	 *
	 * @param uuid the uuid of this profile work experience
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this profile work experience.
	 *
	 * @return the ID of this profile work experience
	 */
	public long getId();

	/**
	 * Sets the ID of this profile work experience.
	 *
	 * @param Id the ID of this profile work experience
	 */
	public void setId(long Id);

	/**
	 * Returns the group ID of this profile work experience.
	 *
	 * @return the group ID of this profile work experience
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this profile work experience.
	 *
	 * @param groupId the group ID of this profile work experience
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this profile work experience.
	 *
	 * @return the company ID of this profile work experience
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this profile work experience.
	 *
	 * @param companyId the company ID of this profile work experience
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this profile work experience.
	 *
	 * @return the user ID of this profile work experience
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this profile work experience.
	 *
	 * @param userId the user ID of this profile work experience
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this profile work experience.
	 *
	 * @return the user uuid of this profile work experience
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this profile work experience.
	 *
	 * @param userUuid the user uuid of this profile work experience
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this profile work experience.
	 *
	 * @return the user name of this profile work experience
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this profile work experience.
	 *
	 * @param userName the user name of this profile work experience
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this profile work experience.
	 *
	 * @return the create date of this profile work experience
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this profile work experience.
	 *
	 * @param createDate the create date of this profile work experience
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this profile work experience.
	 *
	 * @return the modified date of this profile work experience
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this profile work experience.
	 *
	 * @param modifiedDate the modified date of this profile work experience
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the profile ID of this profile work experience.
	 *
	 * @return the profile ID of this profile work experience
	 */
	public long getProfileId();

	/**
	 * Sets the profile ID of this profile work experience.
	 *
	 * @param profileId the profile ID of this profile work experience
	 */
	public void setProfileId(long profileId);

	/**
	 * Returns the title of this profile work experience.
	 *
	 * @return the title of this profile work experience
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this profile work experience.
	 *
	 * @param title the title of this profile work experience
	 */
	public void setTitle(String title);

	/**
	 * Returns the company of this profile work experience.
	 *
	 * @return the company of this profile work experience
	 */
	@AutoEscape
	public String getCompany();

	/**
	 * Sets the company of this profile work experience.
	 *
	 * @param company the company of this profile work experience
	 */
	public void setCompany(String company);

	/**
	 * Returns the location of this profile work experience.
	 *
	 * @return the location of this profile work experience
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this profile work experience.
	 *
	 * @param location the location of this profile work experience
	 */
	public void setLocation(String location);

	/**
	 * Returns the start date of this profile work experience.
	 *
	 * @return the start date of this profile work experience
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this profile work experience.
	 *
	 * @param startDate the start date of this profile work experience
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this profile work experience.
	 *
	 * @return the end date of this profile work experience
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this profile work experience.
	 *
	 * @param endDate the end date of this profile work experience
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the description of this profile work experience.
	 *
	 * @return the description of this profile work experience
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this profile work experience.
	 *
	 * @param description the description of this profile work experience
	 */
	public void setDescription(String description);

	/**
	 * Returns the current work status of this profile work experience.
	 *
	 * @return the current work status of this profile work experience
	 */
	@AutoEscape
	public String getCurrentWorkStatus();

	/**
	 * Sets the current work status of this profile work experience.
	 *
	 * @param currentWorkStatus the current work status of this profile work experience
	 */
	public void setCurrentWorkStatus(String currentWorkStatus);

	/**
	 * Returns the work experience of this profile work experience.
	 *
	 * @return the work experience of this profile work experience
	 */
	@AutoEscape
	public String getWorkExperience();

	/**
	 * Sets the work experience of this profile work experience.
	 *
	 * @param workExperience the work experience of this profile work experience
	 */
	public void setWorkExperience(String workExperience);

}